spring.application.name=ticket-api

server.port=8081

spring.jpa.show-sql=true
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none

spring.datasource.url=${TICKET_DB_URL:jdbc:postgresql://localhost:55433/ticketdb}
spring.datasource.username=postgres-user
spring.datasource.password=postgres-password

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.clean-disabled=true