services:
  user-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-password
      POSTGRES_DB: userdb
    ports:
      - "55432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

  ticket-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-password
      POSTGRES_DB: ticketdb
    ports:
      - "55433:5432"
    volumes:
      - ticket_db_data:/var/lib/postgresql/data

volumes:
  user_db_data:
  ticket_db_data: