spring.application.name=cobaia

app.user.default.roles=ROLE_USER,ROLE_GUEST,ROLE_VIEWER

# Configurações JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.generate-ddl=false
# TODO: usar propriedade funcionamento antigo
spring.jpa.hibernate.ddl-auto=none

# Configuração para usar banco de dados SQLite:
# spring.datasource.url=jdbc:sqlite:db.sqlite
# spring.datasource.url=jdbc:sqlite::memory:
# spring.datasource.driver-class-name=org.sqlite.JDBC
# spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# :jdbc:postgresql://localhost:55432/cobaia
# spring.datasource.url=${POSTGRES_URL}
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/cobaia}
spring.datasource.username=postgres-user
spring.datasource.password=postgres-password
# declarar o driver é opcional para postgres
# spring.datasource.driver-class-name=org.postgresql.PostgreSQLDriver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
spring.flyway.clean-disabled=true
spring.flyway.validate-on-migrate=true


# Configuração para usar banco de dados H2 em memória:
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=sasa
# spring.h2.console.enabled=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql