# USER API ================================================================

@host=localhost:8080

# AuthController
### Autenticar e receber um TOKEN
POST /api/auth/login HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "username": "novo",
    "password": "1234RT56"
}

### Sair
POST /api/auth/logout HTTP/1.1
Host: {{host}}
Authorization: Bearer 0225c6df-d105-4786-acdc-11286a24487a

# USERS ===================================================================

### Listar usuários
GET /api/v1/users HTTP/1.1
Host: {{host}}
Accept: application/json

### Listar usuários (autenticado)
GET /api/v1/users HTTP/1.1
Host: {{host}}
Accept: application/json
Authorization: Bearer e8e15551-9fbe-40f7-87da-aa9de6f8939e
### Criar usuário válido
POST /api/v1/users HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "email": "novoa@email.com",
    "password": "1234RT56",
    "handle": "novoa",
    "name": "Novoa Usuário",
    "roles": [
        "ROLE_USER"
    ],
    "company": "Empresa"
}

### Criar usuário inválido
POST /api/v1/users HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "email": "novo@email.com",
    "password": "1234",
    "handle": "novo",
    "name": "Novo Usuário",
    "roles": [
        "ROLE_USER"
    ],
    "company": "Empresa"
}

# INTEGRAÇÃO USER -> TICKET ===============================================

### Criar usuário (deve gerar automaticamente um ticket)
POST /api/v1/users HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "email": "ticket@email.com",
    "password": "1234RT56",
    "handle": "ticketuser",
    "name": "Usuário Ticket",
    "roles": [
        "ROLE_USER"
    ],
    "company": "Empresa Ticket"
}

# VULNERABILITY REPORTS ====================================================

### Primeiros 10 relatórios
GET /api/v1/vulnerability-reports HTTP/1.1
Host: {{host}}
Accept: application/json

### Terceira página
GET /api/v1/vulnerability-reports?page=3&size=10 HTTP/1.1
Host: {{host}}
Accept: application/json