version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - postgres-server
#      - mongo
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres-server:5432/cobaia
#      MONGO_URL: mongodb://mongo:27017/cobaia
