services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - user-db
      - ticket-db
    environment:
      USER_DB_URL: jdbc:postgresql://user-db:5432/userdb
      TICKET_DB_URL: jdbc:postgresql://ticket-db:5432/ticketdb