@host=localhost:8082

###
POST /api/v1/notifications HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "destinatarios": [
        "joao@email.com",
        "maria@email.com"
    ],
    "assunto": "Novo Ticket",
    "mensagem": "Seu ticket foi criado."
}